//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace EndpointChecker
{

    public partial class EndpointCheck : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fIPaddress;
        public string IPaddress
        {
            get { return fIPaddress; }
            set { SetPropertyValue<string>(nameof(IPaddress), ref fIPaddress, value); }
        }
        string fPlatform;
        public string Platform
        {
            get { return fPlatform; }
            set { SetPropertyValue<string>(nameof(Platform), ref fPlatform, value); }
        }
        bool fSuccess;
        public bool Success
        {
            get { return fSuccess; }
            set { SetPropertyValue<bool>(nameof(Success), ref fSuccess, value); }
        }
        string fError;
        public string Error
        {
            get { return fError; }
            set { SetPropertyValue<string>(nameof(Error), ref fError, value); }
        }
        DateTime fStartTime;
        public DateTime StartTime
        {
            get { return fStartTime; }
            set { SetPropertyValue<DateTime>(nameof(StartTime), ref fStartTime, value); }
        }
        DateTime fEndTime;
        public DateTime EndTime
        {
            get { return fEndTime; }
            set { SetPropertyValue<DateTime>(nameof(EndTime), ref fEndTime, value); }
        }
    }

}
